# Generated by Django 3.2 on 2021-04-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(max_length=255, verbose_name='Setting')),
                ('value', models.TextField(verbose_name='Value')),
            ],
        ),
    ]
